baseURL = 'https://halfoncloud.com/'
languageCode = 'en-us'
title = 'HalfOnCloud'

[params]
  author = "Radu Bogdan"
  description = "IT tutorials, automation scripts, and Microsoft technology insights"
  # Set default theme to dark
  defaultTheme = "dark"
  
# Logo configuration (separate section, not nested)
[params.logo]
  text = "HalfOnCloud"

[markup]
  _merge = "deep"

[build]
  _merge = "deep"

# Main menu configuration
[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 10
  
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
  
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 30

[module]
  [[module.imports]]
    path = "github.com/schnerring/hugo-theme-gruvbox"
  
  [[module.mounts]]
    source = "node_modules/prismjs"
    target = "assets/prismjs"
  [[module.mounts]]
    source = "node_modules/prism-themes/themes"
    target = "assets/prism-themes"
  [[module.mounts]]
    source = "node_modules/typeface-fira-code/files"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/typeface-roboto-slab/files"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/@tabler/icons/icons"
    target = "assets/tabler-icons"
  [[module.mounts]]
    source = "node_modules/simple-icons/icons"
    target = "assets/simple-icons"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"