baseURL = 'https://halfoncloud.com/'
languageCode = 'en-us'
title = 'HalfOnCloud'
copyright = "2025 Radu Bogdan :: HalfOnCloud"
theme = 'terminal'
summaryLength = 100

[params]
  themeColor = "orange"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = false
  description = "IT tutorials, automation scripts, and Microsoft technology insights"
  author = "Radu"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

[languages]
  [languages.en]
    languageName = "English"
    [languages.en.params]
      readMore = "Read More"
      readOtherPosts = "Read other posts"
    [languages.en.params.logo]
      logoText = "HalfOnCloud "
      logoCursor = "|"